### PR TITLE
0.8.0-beta1 Update

### PR DESCRIPTION
**Pull request by daudix**

### CODE REVIEW

**Comment by 0xMRTT** [comment]
Is it ready?

**Comment by 0xMRTT** [comment]
Also by the way do you have access to the repo or no ?

**Comment by daudix** [comment]
Nope, need to add flatpak-spawn to linter and then something with cache

**Comment by daudix** [comment]
> Also by the way do you have access to the repo or no ?

Yep I have access

**Comment by 0xMRTT** [comment]
Nice 👍

**Comment by daudix** [comment]
https://github.com/flathub/flatpak-builder-lint/pull/143

**Comment by orowith2os** [comment]
bot, build com.github.GradienceTeam.Gradience

**Pull request merged**
