### PR TITLE
release: 0.3.3

### PR DESCRIPTION
**Pull request by daudix**

### CODE REVIEW

**Comment by LyesSaadi** [comment]
uhhhh, wat?

**Comment by daudix** [comment]
Smol change xD

**Comment by LyesSaadi** [comment]
uh xD ? Why should this be merged xD ?

**Comment by daudix** [comment]
Why not?

**Comment by LyesSaadi** [comment]
xDDD

**Comment by LyesSaadi** [comment]
Should I merge it now, or is it still a WIP xD ?

**Comment by daudix** [comment]
It can go with `0.3.3`

**Comment by daudix** [comment]
bot, build

**Comment by daudix** [comment]
Alright, everything went smoothly, merge time @LyesSaadi!

**Pull request merged**
